inherit_gem:
 bixby: bixby_default.yml

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'spec/test_app_templates/**/*'
    - 'vendor/**/*'
    # Resole the issues below
    - 'app/helpers/newspaper_works/breadcrumb_helper.rb'
    - 'app/helpers/newspaper_works/newspaper_works_helper_behavior.rb'
    - 'app/helpers/newspaper_works/newspaper_works_helper_behavior.rb'
    - 'app/models/newspaper_article.rb'
    - 'app/validators/newspaper_works/publication_date_start_end_validator.rb'
    - 'app/validators/newspaper_works/publication_date_validator.rb'
    - 'lib/newspaper_works/data/work_derivatives.rb'
    - 'lib/newspaper_works/data/work_files.rb'
    - 'lib/newspaper_works/ingest.rb'
    - 'lib/newspaper_works/ingest/ndnp/batch_ingester.rb'
    - 'app/indexers/newspaper_issue_indexer.rb'
    - 'lib/newspaper_works/ingest/pdf_pages.rb'
    - 'lib/newspaper_works/page_finder.rb'
    - 'lib/newspaper_works/text_extraction/hocr_reader.rb'
    - 'lib/tasks/newspaper_works_tasks.rake'
    - 'spec/lib/newspaper_works/data/work_derivatives_spec.rb'
    - 'spec/lib/newspaper_works/data/work_files_spec.rb'
    - 'spec/lib/newspaper_works/ingest/ndnp/container_ingester_spec.rb'
    - 'tasks/newspaperworks_dev.rake'

Layout/LineLength:
  Exclude:
    - 'spec/lib/newspaper_works/data/work_derivatives_spec.rb'
    - 'spec/lib/newspaper_works/ingest/ndnp/issue_ingester_spec.rb'
    - 'lib/generators/newspaper_works/catalog_controller_generator.rb'

Lint/ImplicitStringConcatenation:
  Exclude:
    - 'lib/generators/newspaper_works/**/*'

Metrics/AbcSize:
  Exclude:
    - 'spec/model_shared.rb'

Metrics/BlockLength:
  ExcludedMethods: ['included']
  Exclude:
    - 'newspaper_works.gemspec'
    - 'lib/tasks/*.rake'
    - 'spec/**/*.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'spec/model_shared.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/newspaper_works/data/work_derivatives.rb'
    - 'lib/newspaper_works/ingest/ndnp/page_ingester.rb'
    - 'lib/newspaper_works/ingest/lc_publication_info.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/helpers/newspaper_works/breadcrumb_helper.rb'
    - 'lib/generators/newspaper_works/catalog_controller_generator.rb'
    - 'lib/newspaper_works/page_finder.rb'
    - 'lib/newspaper_works/ingest/ndnp/ndnp_mets_helper.rb'
    - 'lib/newspaper_works/ingest/pdf_issue_ingester.rb'
    - 'spec/model_shared.rb'

Naming/PredicateName:
  Exclude:
    - ''

Performance/StringReplacement:
  Exclude:
    - 'app/indexers/concerns/newspaper_works/indexes_full_text.rb'

Style/AsciiComments:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/SymbolArray:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Rails/ApplicationJob:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

# We define custom methods like `find_by_user_key`,
# `find_by_created_date`, etc
Rails/DynamicFindBy:
  Enabled: false

Rails/FilePath:
  Exclude:
    - 'spec/abilities/**/*'

Rails/OutputSafety:
  Exclude:
    - 'lib/generators/newspaper_works/templates/config/initializers/patch_blacklight_advanced_search.rb'
    - 'spec/helpers/newspaper_works_helper_spec.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/abilities/**/*'
    - 'spec/conversions/**/*'
    - 'spec/features/**/*'
    - 'spec/inputs/**/*'
    - 'spec/views/**/*'
    - 'spec/lib/tasks/**/*'

# # By default RSpec/MessageSpies has the following:
# #   Prefer have_received for setting message expectations. Setup form as a spy using allow or instance_spy.
# # The default assumes EnforcedStyle is 'have_received'. Most of our specs are 'receive'
RSpec/MessageSpies:
  Enabled: false

RSpec/InstanceVariable:
  Exclude:
    - 'spec/**/*'

RSpec/ExpectActual:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/ExampleLength:
  Max: 19

Rails/RakeEnvironment:
  Enabled: false